# -*- coding: utf-8 -*-
"""FAI_Module_2_Easy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H18MGuJLIfOqcvGWaIYlC4IW4p_zy761
"""

from flask import Flask, request, jsonify
from google import genai
import os

app = Flask(__name__)

# Get Gemini API key from Render Environment Variables
API_KEY = os.environ.get("GOOGLE_API_KEY")

if not API_KEY:
    raise ValueError("GOOGLE_API_KEY is not configured")

client = genai.Client(api_key=API_KEY)

MODEL = "gemini-2.5-flash"


@app.route("/")
def home():
    return "Interactive Question Generator API is running!"


@app.route("/generate", methods=["POST"])
def generate_questions():

    data = request.get_json()

    topic = data.get("topic")
    number = data.get("number", 5)

    if not topic:
        return jsonify({
            "error": "Topic is required"
        }), 400

    prompt = f"""
Generate {number} short questions about {topic}.

Rules:
- Number each question.
- Keep questions clear and simple.
- Give only the questions.
- Do not provide answers.
"""

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt
    )

    return jsonify({
        "topic": topic,
        "questions": response.text
    })


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
